### ISSUE TITLE
Create linux installer

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix-desktop#206]
- [x] `open with` entry in os file explorer should work
- [x] Entry searchable in the apps drawer in linux
- [x] single install and uninstall script
- [x] Add a path alias like `phcode` to bash rc? - works as is in ubuntu. Might need to add to path for other disctibutions.
- [x] verify in prod.
- [x] https://github.com/phcode-dev/phoenix-desktop/pull/274
- [x] https://github.com/phcode-dev/phoenix-desktop/pull/263
- [x] https://github.com/phcode-dev/phoenix-desktop/pull/264
- [x] https://github.com/phcode-dev/phoenix-desktop/pull/262
- [x] https://github.com/phcode-dev/phoenix-desktop/pull/261

**Comment by ArchangeGabriel** [comment]
Have you considered Flatpak? Brackets used to be packaged like that (https://flathub.org/apps/io.brackets.Brackets). This is likely the easiest way to distribute for all distribution.

**Comment by abose** [comment]
Would love to add flatpack support, but unfortunately we use tauri and it doesnt support it yet: https://tauri.app/v1/api/config/#bundletype

In linux there will most likeley be a single line command line install script, so we might not need to worry about the underlying image format.

**Comment by ArchangeGabriel** [comment]
Well they are discussions around this at https://github.com/tauri-apps/tauri/issues/3619 and https://github.com/tauri-apps/tauri/discussions/4426, one app is already doing so (https://github.com/flathub/in.cinny.Cinny) and there is an open PR to document it: https://github.com/tauri-apps/tauri-docs/pull/1760.

Not related, but I might be interested in looking into packaging for ArchLinux at some point. ;)

**Comment by abose** [comment]
Thanks for that! We will be launching betas this month, do check it out and raise any issues/feedback.

**Comment by abose** [comment]
This is done. In Linux we will be distributing as a script that installs portable binaries instead of app-images. 

Appimages have degraded performance due to mount of appimage virtual disc which hampers startup time, 200+mb binary size as it needs to package all deps, consume a lot more memory and is generally not a good ux as we hoped it would. Also it wont work in distributions that does not support app image.

Our new installer works with native built portable binaries that takes advantage of the native OS libraries, have a much more wider compatibility, quick start times and is much more resource efficient.

The new installers coming end of this month is installed via terminal with a single line command. Tested working in:
1. Ubuntu 20+
2. Kubuntu 22+
3. popos 22+
4. fedora 34+
5. Arch Linux
6. debian
7. centos
8. linux Mint
Supports GNOME and KDE.
