### ISSUE TITLE
Tauri And Node integration research

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix-desktop#3]
@charlypa completed node integration research and confirmed that nodejs can be packaged and executed inside the Tauri binary and installer.

This can be done either as a runtime download, or packaged binary Tauri sidecar or as a packed asset.  We are leaning towards a packaged asset-based deployment.
* Downloading at runtime was ruled out as it would mean the installer will not be self-contained for offline use.
* sidecar presented with problems as we need to package large number of node files and sidecar looks to be specifically tailed to packaging single executables.
* Assets can be any random file and can be packaged and deployed to any os.

All the above mechanisms have been tested and validated as feasible.

**Comment by charlypa** [comment]
How to bundle node with Tauri.
1. Download node binary from https://nodejs.org/en/download/
2. Extract the contents to the `src-tauri` folder
3. Add the following entries to `tauri-conf.json1 ```    "resources": ["./node/*"],
      "shortDescription": "",```
4. Build  tauri.

**Comment by charlypa** [comment]
Why not SideCar?
The sidecar is for a single binary.`node` has a large number of individual folders and javascript, so it is pretty challenging to bundle node to a single binary.

**Comment by ScanuNicco** [comment]
I'm wondering if it's possible to allow for extensions to be written in Rust at some point in the future.

**Comment by abose** [comment]
Node is integrated into phcode. Node management layer under construction.

Closing as node integration is done and is currently packaged as a sidecar with tauri in phoenix-desktop.

See https://github.com/phcode-dev/phoenix-desktop/issues/93 for further tracking.
