### ISSUE TITLE
installations broken in Kali linux

### ISSUE THREAD

**Issue by Salah-XD** [phcode-dev/phoenix-desktop#464]

**Comment by abose** [comment]
Did it work before in kali linux? We have not tested it in kali linux yet.

**Comment by abose** [comment]
We are working on adding support for kali linux rhis month.

**Comment by Salah-XD** [comment]
> Did it work before in kali linux? We have not tested it in kali linux yet.

No it did'nt

**Comment by charlypa** [comment]
@Salah-XD 
We have added support for kali linux
https://github.com/phcode-dev/phoenix-desktop/pull/490
