### ISSUE TITLE
Linux Mint dependencies outdated.

### ISSUE THREAD

**Issue by agoodfellow123** [phcode-dev/phoenix-desktop#488]
### Describe the bug

I have tried both of the releases here and the installer.sh in the main site. Dependencies requires update for Ubuntu 24.04 and its derivatives.

### Reproduction

> ~ $ sudo apt install libgtk-3-0 libwebkit2gtk-4.0-37
[sudo] password for user:           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libgtk-3-0t64' instead of 'libgtk-3-0'
E: Unable to locate package libwebkit2gtk-4.0-37
E: Couldn't find any package by glob 'libwebkit2gtk-4.0-37'

### Expected behavior

Compiling.

### OS, Browser and Phoenix versions

Linux Mint 22, Desktop, Desktop client, Release v3.8.8

**Comment by charlypa** [comment]
@agoodfellow123 
Support for Linux mint 22 has been added to install script. Please try installing using script again and see if it works
https://github.com/phcode-dev/phoenix-desktop/pull/489

**Comment by agoodfellow123** [comment]
It did work, thank you for the quick fix!

**Comment by xandark** [comment]
Not sure if the Phoenix team is interested in adding a similar fix for installing Phoenix within the **KDE neon** distro, which is a distro that uses up-to-date KDE libraries but is based on Ubuntu for everything else. 

So to get Phoenix to install, I had to modify the install script in the check_os_version() function adding the "neon" check:

```
        if [[ "$ID" = "ubuntu" && "$VERSION_ID" = "24.04" ]] || 
           [[ "$ID" = "neon"   && "$VERSION_ID" = "24.04" ]] ||
           [[ "$ID" = "linuxmint" && "$VERSION_ID" = "22" ]] ||
           ([[ "$ID" = "kali" ]] && [[ "$VERSION_ID" > "2024.2" ]] || [[ "$VERSION_ID" == "2024.2" ]]); then
            return 0  # Ubuntu 24.04, Linux Mint 22, or Kali Linux 2024.2 or newer detected
        fi

```

**Comment by charlypa** [comment]
@xandark 
Thanks for feedback we will add this after testing
