### ISSUE TITLE
Replace removes extra characters

### ISSUE THREAD

**Issue by github-monkey** [phcode-dev/phoenix-desktop#511]
### Describe the bug

When using Replace (in Files) unexpected characters are matched and removed.

### Reproduction

Given this block:

    <div class="frame-styling-frame-icons" id="circleGrid1">
    </div>
</body>
</html>

When you try to Replace (in Files) .frame-styling-frame-icons with .icon.grid, the result is that the leading quotation mark of the target string is removed. Looking at the code block before clicking replace, Replace can be seen matching the leading " in the block as the . of the target string.

Turning:

    <div class=_"frame-styling-frame-icons"_ id="circleGrid1">
    </div>
</body>
</html>

Into:

    <div class=.icon.grid" id="circleGrid1">
    </div>
</body>
</html>

### OS, Browser and Phoenix versions

Windows 11
desktop
Chrome Version 128.0.6613.84 (Official Build) (64-bit)
Phoenix Code Release 3.8 build 3.8.8-20449

**Comment by abose** [comment]
@github-monkey It is likely that Regex mode is enabled which will treat the search string as a regex. Please click below image to disable.
![Screenshot_20240828_080401_Chrome.jpg](https://github.com/user-attachments/assets/338ad8d4-36b6-4251-854b-3272302247da)

**Comment by github-monkey** [comment]
You were right. Thank you.
