### ISSUE TITLE
App description shows instead of app name in file association dialog

### ISSUE THREAD

**Issue by devvaannsh** [phcode-dev/phoenix-desktop#535]
### Describe the bug

When trying to open a file (using the "open with" button), the system file association dialog shows the description of Phoenix ("Phoenix is a modern open-source IDE for the web, built for the browser") instead of the app name. This could cause confusion for users. Ideally, the app name should be displayed instead of the description.
![Screenshot 2024-09-04 233137](https://github.com/user-attachments/assets/764c3577-9b29-4fa0-9055-adb5739d947e)

Along with "Opening with phoenix" option doesn't even show up for some files with extensions like '.py', '.config'.
![Screenshot 2024-09-04 234159](https://github.com/user-attachments/assets/8393069c-68e1-41bc-b1fb-e957dca4557d)

### Reproduction

1. Right-click on a file (ex :- file.html)
2. Select "Open with..."
3. Notice that Phoenix shows its description instead of the app name.

### Expected behavior

The app name ("Phoenix") should appear in the list, not the description.

### OS, Browser and Phoenix versions

OS :- Windows 11
Phoenix version : Release 3.9 build 3.9.1-20553
build timestamp: 2024-09-06T07:44:35.003Z

**Comment by abose** [comment]
Fix for dev builds. to verify in prod.
