### ISSUE TITLE
Application terminates on startup with error

### ISSUE THREAD

**Issue by atarax42** [phcode-dev/phoenix-desktop#566]
### Describe the bug

When starting the application it terminates immediately with this error message in stderr:
`error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory`

### OS, Browser and Phoenix versions

OS: Linux Mint 22
Phoenix Code Version: 3.10.0
From: phoenix-code_3.10.0_amd64_linux_bin-GLIBC-2.35.tar.gz
GLIBC is version 2.39-0ubuntu8.3

**Comment by abose** [comment]
Thanks for reporting the issue @atarax42 
Related to https://github.com/phcode-dev/phoenix/issues/1981
Please track fix in that issue.
Closing as duplicate

**Comment by charlypa** [comment]
@atarax42  This issue is fixed now. Would you try installation again and see if it fix works for you

**Comment by atarax42** [comment]
I would if there was a new release. I don't know how to install from source...

**Comment by abose** [comment]
The release script has been updated. Just run the one luner from phcode.io
