### ISSUE TITLE
Installer generation, update support

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix-desktop#72]

**Comment by charlypa** [comment]
We employ Tauri for the creation of native installers applicable to Windows, Mac, and Linux systems. Windows utilizes NSIS, Mac engages both arm and amd64 dmg, while Linux operates via appimage.

Through GitHub workflows, we certify our installers. Windows installations utilize an EV signature, and for Mac, we leverage Apple's notarization service. As of the present, Linux does not necessitate any notarization process.

In addition, Tauri inherently devises updates, distributed as a bundled package. This feature activates notification alerts, promptly informing the user regarding any essential updates.

**Comment by abose** [comment]
When a new release is published through GitHub Releases, a GitHub Action will automatically generate a pull request, as shown in this example: https://github.com/phcode-dev/phoenix-desktop/pull/68. This pull request contains all the necessary files needed for the updater to perform updates on all installed builds, bringing them to the latest released version.

After the pull request is merged, we need to perform a subsequent merge, merging the main branch into the update-notification branch. This action is crucial as it triggers the update process for all installed builds, ensuring they are updated to the latest released version. Before this merge, manual quality assurance (QA) and sanity tests should be conducted to ensure the update process goes smoothly.
